stages:
  - test_backend_api

test_backend_api:
  stage: test_backend_api
  script:
    - apt update
    - apt install -y curl
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - echo "Run backend API tests"
    - ./scripts/test_backend_API.sh