[project]
name = "svtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "flask",
  "flask_sqlalchemy",
  "flask_cors",
  "mariadb",
  "pandas",
  "flask_session",
  "requests",
  "pygame",
  "opencv-python",
  "pillow",
  "qrcode",
  "pyserial",
  "pyzbar",
  "rich",
  "jinja2>=3.1.6",
  "sh>=2.2.2",
]

[tool.ruff]
indent-width = 2
