services:
  inventory_db:
    container_name: inventory_db
    image: "docker.io/library/mariadb:10.11"
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MARIADB_DISABLE_CHOWN: 1
    volumes:
      - ./inventory_data/mariadb/data:/var/lib/mysql:Z
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  inventory_server:
    image: inventoryserver:latest
    container_name: inventory-server
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./media:/app/media
    environment:
      DB_HOST: inventory_db
      DB_PORT: 3307
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - inventory_db

  inventory_camera:
    image: inventorycamera:latest
    container_name: inventory-camera
    restart: unless-stopped
    ports:
      - "5050:5050"
    devices:
      - "/dev/video0:/dev/video0"   
    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
    volumes:
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
      - /run/user/${UID}/pulse/native:/tmp/pulseaudio.socket
    group_add:
      - audio
      - video
    privileged: true 
    networks:
      - invnet

  inventory_printer:
    image: inventoryprinter:latest
    container_name: inventory-printer
    restart: unless-stopped
    ports:
      - "5100:5100" 
    volumes:
      - /var/run/dbus:/var/run/dbus
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 
      - /dev/hci0:/dev/hci0 
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
    privileged: true 
    networks:
      - invnet

networks:
  invnet:

volumes:
  inventory_data:
    driver: local
