services:
  inventory_db:
    container_name: inventory_db
    image: "mariadb:10.5"
    restart: unless-stopped
    ports:
      - '46123:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./volumes/mariadb/data:/var/lib/mysql
      - ./init-db-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
