[project]
name = "camera_server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "flask",
  "flask_sqlalchemy",
  "flask_cors",
  "flask_session",
  "requests",
  "opencv-python",
  "pillow",
  "pyzbar",
  "qrcode",
  "pygame",
  "rich"
]

[tool.ruff]
indent-width = 2
